### ISSUE TITLE
Support RxPHP 1.5.0

### ISSUE THREAD

**Issue by davidwdan** [Domraider/rxnet#17]
I opened an [issue](https://github.com/ReactiveX/RxPHP/issues/105) on RxPHP to address the compatibility [issue](https://github.com/Domraider/rxnet/commit/7ea23c5ecfaa58f5069f6cbc7cb4a1e537a1552b) you're experiencing.

It should be safe for you to drop the [default empty array](https://github.com/Domraider/rxnet/blob/master/src/Rxnet/Http/Http.php#L69) since that is a required property and will always have a value.

**Comment by madmatah** [comment]
Thank you very much @davidwdan
