### ISSUE TITLE
RabbitQueue has an unused `opts` parameter

### ISSUE THREAD

**Issue by krichprollsch** [Domraider/rxnet#32]
As far I can read [here](https://github.com/Domraider/rxnet/blob/master/src/Rxnet/RabbitMq/RabbitQueue.php#L27), the constructor of `RabbitQueue` expects an array of options which are never use.

Maybe you could safely remove this parameter? Or if these options should be used into the creation step of the queue, you should merge them with the `create`'s options parameter.

**Comment by Vinceveve** [comment]
For now I remove it from __construct() we will see if it's needed to have a global option

**Comment by krichprollsch** [comment]
:+1: So don't forget to remove it from [here](https://github.com/Domraider/rxnet/blob/master/src/Rxnet/RabbitMq/RabbitMq.php#L144) too ;)

**Comment by krichprollsch** [comment]
And I guess it should be the same for exchange [[1]](https://github.com/Domraider/rxnet/blob/master/src/Rxnet/RabbitMq/RabbitExchange.php#L31)
